#!/bin/bash

# 通用路径
ROOT_PATH=$PATH_ZWTL_ROOT
WORK_PATH=$PATH_ZWTL_HOST/zwscp

# 专用文件
THIS_FILE=$ROOT_PATH/zwping
LINK_FILE=$PATH_ZWTL_INST/kping

# WORK文件
HOST_FILE=$WORK_PATH/hosts
source $HOST_FILE 2> /dev/null


########################################################################################################
# 打印用法
########################################################################################################
function print_usage()
{
    echo "cmd           [arg]            [val]     description"
    echo "----------    -------------    ------    --------------"
	echo "kping         -a/-s/-b/-t      file      ping host"
	echo "kping         -e                         edit host"
}

########################################################################################################
# 获取文件
########################################################################################################
function put_file()
{	
	case $1 in
		-a)
		HOST_PATH=$HOST_ZW
		;;

		-s)
		HOST_PATH=$HOST_SERVER
		;;

		-b)
		HOST_PATH=$HOST_BOARD
		;;

		-t)
		HOST_PATH=$HOST_TMP
		;;
	esac

	arr=(`echo $HOST_PATH | tr ':' ' '`)
	HOST=${arr[0]}
	IP=${HOST#*@}
	ping $IP 
}

########################################################################################################
# 程序入口
########################################################################################################
function zwput_entry()
{
	# 如果没写参数, 或帮助命令, 则打印帮助信息
	if [ $# = 0 ] || [ $1 = '-h' ] || [ $1 = '--help' ];then
		print_usage
		exit 1
	fi

	case $1 in
		-init)
		ln -s $THIS_FILE $LINK_FILE 2> /dev/null
		;;

		-edit)
		vi $THIS_FILE
		;;

		-e)
		vi $HOST_FILE
		;;

		*)
		put_file $@
		;;
	esac
}
zwput_entry $@

