#!/bin/bash

# 通用路径
ROOT_PATH=$PATH_ZWTL_ROOT
CORE_PATH=$ROOT_PATH/core/zwpp

# 专用文件
THIS_FILE=$ROOT_PATH/zwpp
LINK_FILE=$PATH_ZWTL_INST/pp

# 默认文件
DEFAULT_FILE=$CORE_PATH/current

########################################################################################################
# 帮助选项
########################################################################################################
function print_usage()
{
    echo "cmd           [arg]            [val]     description"
    echo "----------    -------------    ------    --------------"
	echo "pp                             file      look file note"
}

########################################################################################################
# 查看文件
########################################################################################################
function look_file()
{
	if [ $# = 1 ];then
		ls -p $CORE_PATH
	else
		ls -p $CORE_PATH/$2
	fi
}

########################################################################################################
# zwpp边界
########################################################################################################
function zwpp_edit()
{
	if [ $# = 2 ];then
		vi ${CORE_PATH}/$2
		exit 1
	fi

	vi $DEFAULT_FILE
}

########################################################################################################
# 根据情况提示
########################################################################################################
function do_prompt()
{
	FILE=$CORE_PATH/$1
	KEY={$2

	case $# in
		1)
		if [ -f $FILE ]; then
			cat $FILE						
		else
			cd $CORE_PATH
			grep --color=auto $1 * -nr
		fi
		;;

		2)				
		cat $FILE | grep --color=auto $KEY -A 5	# 查看和key相关得信息
		;;

		3)
		cat $FILE | grep --color=auto $KEY -A $3	# 查看和key相关得信息
		;;
	esac
}

########################################################################################################
# 程序入口
########################################################################################################
function zwpp_entry()
{
	if [ $# = 0 ];then
		cat $DEFAULT_FILE
		exit 1
	fi

	case $1 in
		-h)
		print_usage
		;;

		.)
        cat $PWD/zw.pp
		;;

		-init)
		ln -s $THIS_FILE $LINK_FILE 2> /dev/null
		;;

		-l)
		look_file $@
		;;

		-ls)
		look_file $@
		;;

		-cd)
		cd $CORE_PATH
		;;

		-e)
		zwpp_edit $@
		;;

		-grep)
		cd $CORE_PATH
		grep $2 -nr
		;;

		-edit)
		vi $THIS_FILE
		;;

		p)
		cat $CORE_PATH/eval/rk3568
		;;

		-p)
		vi $CORE_PATH/eval/rk3568
		;;

		*) 
		do_prompt $@
		;;
	esac
}

zwpp_entry $@
