#!/bin/bash

# 通用路径
ROOT_PATH=$PATH_ZWTL_ROOT
CORE_PATH=$ROOT_PATH/core/zwpp

# 专用文件
THIS_FILE=$ROOT_PATH/zwpp
LINK_FILE=$PATH_ZWTL_INST/pp

# 导入文件
source $ROOT_PATH/tools/scripts/utils
source $ROOT_PATH/tools/scripts/com_p

########################################################################################################
# 帮助选项
########################################################################################################
function print_usage()
{
    echo "[Usage]: "
    printf "%-20s%-50s\n" "	pp <key>"           "match all file to key"
    printf "%-20s%-50s\n" "	pp <file> <key>"    "match target file to key"
}

############################################################### propt
# 提示文件
function prompt_file()
{
	cd ${CORE_PATH}
	RES=$(find -name $1)
	FILE=$CORE_PATH/$RES

	if [ -f $FILE ]; then
		cat $FILE						
	else
		cd $CORE_PATH
		grep --color=auto $1 * -nr
	fi
}

# 提示上下文
function prompt_file_context()
{
	cd ${CORE_PATH}
	RES=$(find -name $1)

	if [[ $# == 2 ]]; then
		grep --color=auto $2 $RES 5
	else
		grep --color=auto $2 $RES -A $3
	fi
}

# 提示
function do_prompt()
{
	case $# in
		1) prompt_file $@ ;;
		*) prompt_file_context $@ ;;
	esac
}

########################################################################################################
# 程序入口
########################################################################################################
function zwpp_entry()
{
	if [ $# = 0 ];then
		cat $DEFAULT_FILE
		exit 1
	fi

	case $1 in
		-h)    print_usage ;;
		-init) common_init ;;
		-x)    do_x $CORE_PATH $@ ;;
		-e)    p_edit $2 ;;
		-edit) edit_file $THIS_FILE ;;
		-cd)   cd_dir $CORE_PATH ;;
		*)     do_prompt $@ ;;
	esac
}

zwpp_entry $@
