#!/bin/bash
# 通用路径
ROOT_PATH=$PATH_ZWTL_ROOT
CORE_PATH=$ROOT_PATH/core/zwsp

# 专用文件
THIS_FILE=$ROOT_PATH/zwsp
LINK_FILE=$PATH_ZWTL_INST/sp


# 获取模板CLASS
SAMPLE_CLASS=$(ls -l ${CORE_PATH} |awk '/^d/ {print $NF}')

########################################################################################################
# 帮助选项
########################################################################################################
function print_usage()
{
	echo "usage : sp <class> <sample>"
	echo ""
	echo "class list:"
	echo ${SAMPLE_CLASS}
	echo ""
	echo "optioin list:"
	echo "-h     help"
	echo "-ls    list sample      sp -ls <class>"
	echo "-rp    replace key      sp -rp <dir/file> <key>"
}

########################################################################################################
# 显示模板
########################################################################################################
function list_sample()
{
	local KEY
	local STR
	local CLASS=$2
	local FILE_SP=$CORE_PATH/$CLASS/note.sp

	# 读取文件
	while read rows
	do
		KEY=`echo $rows | cut -d \" -f 1`
		STR=`echo $rows | cut -d \" -f 2`
		printf "%-20s" $KEY
		echo $STR
	done < $FILE_SP
}



########################################################################################################
# 模板入口
########################################################################################################
function zwsample_entry()
{
	# 如果参数个数小于2, 打印提示
	if [ $# = 0 ];then
    	print_usage $@
		exit 1
	fi

	if [ $# = 1 ]; then
		echo $CORE_PATH
		grep --color=auto $1 $CORE_PATH -nr
		exit 1
	fi

	# 参数判断
	case $1 in
		-h)
		print_usage $@
		;;

		-init)
		ln -s $THIS_FILE $LINK_FILE 2> /dev/null
		;;

		-edit)
		vi $THIS_FILE
		;;

		-cd)
		cd $CORE_PATH
		;;

		-ls)
		list_sample $@
		;;

		*)
		cp -rf ${CORE_PATH}/$1/$2 .
		;;
	esac
}

zwsample_entry $@
