#!/bin/bash

# 通用路径
ROOT_PATH=$PATH_ZWTL_ROOT

# 专用文件
THIS_FILE=$ROOT_PATH/zwstr
LINK_FILE=$PATH_ZWTL_INST/str

########################################################################################################
# 打印用法
########################################################################################################
function print_usage()
{
    echo "cmd           [arg]    [val]            description"
    echo "----------    -----    -------------    --------------"
	echo "str           -f       <file> <xxx>     replace file"
	echo "str           -d       <dir> <xxx>      replace dir"
}

########################################################################################################
# 替换文本
########################################################################################################
function replace_file()
{
    if [ $# != 3 ]; then
        print_usage
        exit
    fi

    local FILE=$2
    local LOWER=$3
    local UPPER=`echo $3 | tr a-z A-Z`

    # 替换文件
    sed -i "s/xxx/$LOWER/g" $FILE

    # 重命名文件
    new=${FILE/xxx/$LOWER}
    mv $FILE $new
}

########################################################################################################
# 替换文件夹
########################################################################################################
function replace_dir()
{
    if [ $# != 3 ]; then
        print_usage
        exit
    fi

    local DIR=$2
    local LOWER=$3
    local UPPER=`echo $3 | tr a-z A-Z`

    # 替换文件
    sed -i "s/xxx/$LOWER/g" `grep xxx -lr $DIR` 2> /dev/null
    sed -i "s/XXX/$UPPER/g" `grep XXX -lr $DIR` 2> /dev/null

    # 替换文件名
    res=$(find $DIR -type f -name xxx*)
    readarray -t arr <<< "$res"

    for item in "${arr[@]}"; do
        new=${item/xxx/$LOWER}
        mv $item $new
    done
}

########################################################################################################
# 程序入口
########################################################################################################
function zwstr_entry()
{
    case $1 in
        -edit)
        vi $THIS_FILE
        ;;

        -init)
        ln -s $THIS_FILE $LINK_FILE 2> /dev/null
        ;;

        -f)
        replace_file $@
        ;;

        -d)
        replace_dir $@
        ;;

        *)
        print_usage
        ;;
    esac
}

zwstr_entry $@
