#!/bin/bash

# 通用路径
ROOT_PATH=$(cd `dirname $0`; pwd)
WORK_PATH=$ROOT_PATH/.work

# 专用文件
THIS_FILE=$ROOT_PATH/zwtool

# 本地文件
ENV_FILE=

# 本地变量
RED='\033[0;31m'

########################################################################################################
# 打印使用方法
########################################################################################################
function print_usage()
{
    echo "cmd           arg      description"
    echo "----------    ------   --------------------"
	echo "zwtool        -env     prompt env var"
	echo "zwtool        -lsenv   ls env"
    echo "zwtool        -init    init zwtool"
}


########################################################################################################
# 初始化各个模块
########################################################################################################
function zwtool_module_init()
{
	# 通用工具
	$ROOT_PATH/zwcmd   -init			# 初始化命令工具
	$ROOT_PATH/zwvi    -init			# 初始化编辑工具
	$ROOT_PATH/zwssh   -init			# 初始化SSH工具
	$ROOT_PATH/zwget   -init			# 初始化GET工具
	$ROOT_PATH/zwput   -init			# 初始化PUT工具
	$ROOT_PATH/zwping  -init			# 初始化SSH工具
	$ROOT_PATH/zwcd    -init			# 初始化跳转工具

	# 专用工具
	$ROOT_PATH/zwsp    -init			# 初始化SP工具
	$ROOT_PATH/zwp     -init			# 初始化P工具
	$ROOT_PATH/zwpp    -init			# 初始化PP工具
	$ROOT_PATH/zwcp    -init			# 初始化SP工具
	$ROOT_PATH/zwtar   -init          	# 初始化tar工具
	$ROOT_PATH/zwweb   -init          	# 初始化web工具
	$ROOT_PATH/zwkcmd  -init			# 初始化命令工具
	$ROOT_PATH/zwtbin  -init			# 初始化临时二进制工具
}

########################################################################################################
# 工具初始化
########################################################################################################
function print_zwtool_env()
{
    echo -e "\033[33mSET ENV(.basrc or /etc/profile): \033[0m"
	echo "step1: "
	echo "    source $ENV_FILE"
	echo "step2: "
	echo "    source ~/.bashrc"
	echo "    zwtool -init"
}

########################################################################################################
# 生成env文件
########################################################################################################
function zwtool_create_env()
{
	# 判断host
	if [[ $# != 2 ]]; then
		HOST=host
	else
		HOST=$2
	fi

	# 判断HOST是否存在
	HOST_PATH=$WORK_PATH/$HOST
	ENV_FILE=$HOST_PATH/env

	# 判断主机路径是否存在
	if [ -d "$HOST_PATH" ]; then
		echo -e "\033[33mENV EXIST(.basrc or /etc/profile): \033[0m"
		echo "    source $HOST_PATH/env"
		exit
	fi	

	# 创建环境文件
	mkdir -p $HOST_PATH/bin/zbin
	mkdir -p $HOST_PATH/bin/tbin

	touch $ENV_FILE

	# 添加HOST路径
	echo "export PATH_ZWTL_ROOT=$PWD" >> $ENV_FILE							# 路径 - zwtool root
	echo "export PATH_ZWTL_HOST="$HOST_PATH >> $ENV_FILE					# 路径 - host
	echo 'export PATH_ZWTL_BIN=$PATH_ZWTL_HOST/bin' >> $ENV_FILE			# 路径 - bin
	echo 'export PATH_ZWTL_ZBIN=$PATH_ZWTL_BIN/zbin' >> $ENV_FILE			# 路径 - zbin, 默认程序安装到此处
	echo 'export PATH_ZWTL_TBIN=$PATH_ZWTL_BIN/tbin' >> $ENV_FILE			# 路径 - tbin, 临时程序安装到此处
	echo 'export PATH_ZWTL_INST=$PATH_ZWTL_BIN/zbin' >> $ENV_FILE			# 路径 - inst, 默认程序安装到此处, 目前与zbin同路径
	echo 'export PATH=$PATH:$PATH_ZWTL_ROOT' >> $ENV_FILE					# 导出路径 - 基础环境
	echo 'export PATH=$PATH:$PATH_ZWTL_ZBIN' >> $ENV_FILE					# 导出路径 - zbin
	echo 'export PATH=$PATH:$PATH_ZWTL_TBIN' >> $ENV_FILE                   # 导出路径 - tbin
	echo "alias kd='source zwcd'" >> $ENV_FILE                              # 支持kd
}

########################################################################################################
# 生成env文件
########################################################################################################
function zwtool_set_env()
{
	FILE_SYS=~/.bashrc

	# 设置系统文件
	ENV_VAR="source $ENV_FILE"
	echo $ENV_VAR >> $FILE_SYS
	# exec bash --rcfile ~/.bashrc
}

########################################################################################################
# 环境初始化
########################################################################################################
function zwtool_env_init()
{
	zwtool_create_env $@
	print_zwtool_env
}

########################################################################################################
# 工具初始化
########################################################################################################
function zwtool_start()
{
	zwtool_create_env         # 配置生成环境文件
	zwtool_set_env            # 设置环境
}

########################################################################################################
# 工具初始化
########################################################################################################
function zwtool_init()
{
	if [ -z $PATH_ZWTL_HOST ]; then
		echo -e "    ${RED}ERROR: please [source ~/.bashrc] ${NC}"
		exit
	fi

	# zwtool_create_env         # 配置生成环境文件
	# zwtool_set_env            # 设置环境
	zwtool_module_init        # 初始化各个模块
}

########################################################################################################
# 工具清空
########################################################################################################
function zwtool_clean()
{
	find $ROOT_PATH -type l -delete
	rm -rf $WORK_PATH
}

########################################################################################################
# 程序入口
########################################################################################################
function zwtool_entry()
{
	# 如果没写参数
	if [ $# = 0 ];then
		print_usage
		exit 1
	fi

	case $1 in
        -edit)  vi $THIS_FILE ;;
		-env)   zwtool_env_init $@ ;;
		-start) zwtool_start ;;
		-init)  zwtool_init $@ ;;
		-lsenv) ls $WORK_PATH ;;
		-clean) zwtool_clean ;;
		*)      print_usage ;;
	esac    
}

zwtool_entry $@
