xxx.c            "source file sample"
xxx.h            "head file sample"
app/             "app sample"
module/          "module sample, such as so app [zwstr]"
light/           "light app, pwm + gpio"
frwk_app/        "app framework"
frwk_hal/        "hal framework"
