assembly/        "assembly sample class"
kmod/            "simple kernel module"
kmod_cdev/       "cdev module driver without dts"
kmod_misc/       "misc module driver"
kmod_input/      "input module driver"
kmod_i2c/        "i2c module driver"
kmod_spi/        "spi module driver"
kprobe/          "kprobe sample"
drv_api.c        "api reference"
